# Generated by Django 6.0 on 2026-04-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_dailyactivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
